replicaCount: 1
namespace: myns

image:
  repository: 22752/github-gists
  tag: v6

container:
  port: 8080
  resources:
    requests:
      cpu: 60m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi