apiVersion: v1
kind: Namespace
metadata:
  name: myns

---
apiVersion: v1
kind: Service
metadata:
  name: github-gists
  namespace: myns
spec:
  type: LoadBalancer
  selector:
    app: github-gists
  ports:
  - port: 8000         # External port
    targetPort: 8080   # Port your pod listens on

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-gists
  namespace: myns
  labels:
    app: github-gists
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-gists
  template:
    metadata:
      labels:
        app: github-gists
    spec:
      containers:
        - name: github-gists
          image: 22752/github-gists:v1
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 100m
              memory: 128Mi
