apiVersion: v1
kind: Service
metadata:
  name: github-gists
  namespace: myns
spec:
  type: ClusterIP
  selector:
    app: github-gists
  ports:
  - port: 8000         # External port
    targetPort: 8080   # Port your pod listens on
